title: <p align="center"> Paul Lin </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/Paul_Lin_Resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/paulslin/">LinkedIn</a>
  </p>
  
  <p align="left">
  University of Pennsylvania <br><br>
  Master of Science in Engineering in Computer and Information Science <br><br>
  Certificate in Geographical Information System & Spatial Analysis <br><br>
  Graduation Date - December 2021
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
